name: Nauths
url: nauths.fr

markdown: kramdown
highlighter: rouge
encoding: UTF-8

exclude: [Makefile, Gemfile, dev, export, README.md]

relative_permalinks: false

plugins:
  - jekyll-redirect-from
