name: Nauths
url: nauths.fr

markdown: kramdown
highlighter: rouge
encoding: UTF-8

exclude:
  - README.md
  - Makefile
  - Gemfile
  - Gemfile.lock
  - dev
  - export

relative_permalinks: false

plugins:
  - jekyll-redirect-from
